# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - release
    - .azure-pipelines
    - .vsts.release.yml

pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - release
    - .azure-pipelines
    - .vsts.release.yml

parameters:
- name: version
  type: string
  displayName: Version
  default: 'NotSet'
- name: targetFramework
  displayName: Target framework
  type: string
  default: net8.0
  values:
  - net8.0
  
- name: derivedFrom
  type: string
  displayName: Derived From Version
  default: 'lastMinorRelease'
  values:
  - 'lastMinorRelease'
  
- name: skipTests
  type: boolean
  default: false
  displayName: Skip Tests
# buildStageOnly is useful for testing changes of the build stage which cannot be tested
# in the ci project, like signing, without actually doing a release
- name: buildStageOnly
  type: boolean
  default: false
  displayName: Build Stage Only

- name: onlyGitHubRelease
  type: boolean
  default: false
  displayName: Release only for GitHub

- name: testProxyAgent
  type: boolean
  default: true
  displayName: Test Proxy Agent

- name: disableNotifications
  type: boolean
  default: false
  displayName: Disable Teams Notifications

# Skip CG
variables:
  - name: OneES_JobScannedCount
    value: 1

extends:
  template: /.azure-pipelines/pipeline.yml@self
  parameters:
    branch: $[ stageDependencies.Verify_release.Set_variables.outputs['SetReleaseVariables.releaseBranch'] ]
    test: ${{ not(parameters.skipTests) }}
    sign: true
    publishArtifacts: true
    targetFramework: ${{ parameters.targetFramework }}
    testProxyAgent: ${{ parameters.testProxyAgent }}

    preBuildStages:
      - stage: List
        jobs:
        ################################################################################
        - job: list_blobs
        ################################################################################
          displayName: List Blobs in the test container
          pool:
            name: 1ES-Shared-Hosted-Pool_Windows-Server-2022
            demands: AzurePS
          steps:
          - task: AzurePowerShell@5
            displayName: Execute powershell script
            inputs:
              pwsh: true
              azurePowerShellVersion: 'LatestVersion'
              azureSubscription: 'azure-pipelines-agent-vstsagentpackage-oauth'
              scriptType: 'InlineScript'
              inline: |
                Write-Host "Preloading Azure modules." # This is for better performance, to avoid module-autoloading.
                Import-Module Azure, Az.Accounts, Az.Storage, Az.Cdn -ErrorAction Ignore -PassThru
                Select-AzSubscription -SubscriptionId $(SubscriptionId)
                $storageContext = New-AzStorageContext -StorageAccountName vstsagentpackage -UseConnectedAccount
                $container = "agent"
                Write-Host "container = $container"
                $blobs = Get-AzStorageBlob -Container $container -MaxCount 5 -Context $storageContext
                $blobs | ForEach-Object {
                  Write-Host "Found blob: $($_.Name)"
                }

